// shipagent-frontend/apps/domain-remote/src/app/label-preview/label-preview.component.ts
/**
 * LabelPreviewComponent
 *
 * Port of React LabelPreview.tsx.
 * Renders PDF shipping labels in-browser using ng2-pdf-viewer.
 * Provides download and print actions.
 * Handles loading and error states.
 */

import {
  Component,
  Input,
  ChangeDetectionStrategy,
  signal,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { PdfViewerModule } from 'ng2-pdf-viewer';
import {
  LoadingIconComponent,
  AlertIconComponent,
  PrinterIconComponent,
  DownloadIconComponent,
} from '@shipagent/shared-ui';

@Component({
  selector: 'app-label-preview',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    PdfViewerModule,
    LoadingIconComponent,
    AlertIconComponent,
    PrinterIconComponent,
    DownloadIconComponent,
  ],
  template: `
    <div class="flex flex-col h-full">
      <!-- Header -->
      <div class="flex items-center justify-between px-4 py-3 border-b border-border">
        <h4 class="text-sm font-medium text-foreground">
          {{ title || 'Label Preview' }}
        </h4>
        @if (trackingNumber) {
          <code class="text-xs font-mono text-muted-foreground">{{ trackingNumber }}</code>
        }
      </div>

      <!-- PDF viewer -->
      <div class="flex-1 overflow-y-auto min-h-0 bg-muted/30 p-4">
        @if (isLoading()) {
          <div class="flex flex-col items-center justify-center py-16 text-muted-foreground">
            <sa-icon-loading class="h-8 w-8 animate-spin mb-4" />
            <p class="text-sm">Loading label...</p>
          </div>
        }

        @if (loadError()) {
          <div class="flex flex-col items-center justify-center py-16 text-error">
            <sa-icon-alert class="h-8 w-8 mb-4" />
            <p class="text-sm font-medium mb-2">Failed to load label</p>
            <p class="text-xs text-muted-foreground">{{ loadError() }}</p>
          </div>
        }

        @if (!loadError() && resolvedUrl) {
          <pdf-viewer
            [src]="resolvedUrl"
            [render-text]="false"
            [original-size]="false"
            [fit-to-page]="true"
            [zoom]="1"
            [show-all]="true"
            [page]="1"
            (after-load-complete)="onLoadComplete($event)"
            (error)="onLoadError($event)"
            style="display: block; width: 100%;"
          />
        }
      </div>

      <!-- Footer actions -->
      <div class="flex items-center justify-end gap-2 px-4 py-3 border-t border-border">
        <button
          (click)="handlePrint()"
          [disabled]="isLoading() || !!loadError()"
          class="btn-secondary py-1.5 px-3 flex items-center gap-2 text-sm disabled:opacity-50"
        >
          <sa-icon-printer class="w-4 h-4" />
          <span>Print</span>
        </button>
        <button
          (click)="handleDownload()"
          [disabled]="isLoading() || !!loadError()"
          class="btn-primary py-1.5 px-3 flex items-center gap-2 text-sm disabled:opacity-50"
        >
          <sa-icon-download class="w-4 h-4" />
          <span>Download</span>
        </button>
      </div>
    </div>
  `,
})
export class LabelPreviewComponent implements OnChanges {
  /** Tracking number for single-label view (used to build URL and filename). */
  @Input() trackingNumber?: string;

  /** Job ID for per-row label access. */
  @Input() jobId?: string;

  /** Row number for per-row label access. */
  @Input() rowNumber?: number;

  /** Direct PDF URL (takes precedence over derived URLs). */
  @Input() labelUrl?: string;

  /** Display title in the header. */
  @Input() title?: string;

  readonly isLoading = signal(true);
  readonly loadError = signal<string | null>(null);

  /** Resolved URL computed from inputs. */
  get resolvedUrl(): string {
    if (this.labelUrl) return this.labelUrl;
    if (this.jobId && this.rowNumber != null) {
      return `/api/v1/jobs/${this.jobId}/labels/${this.rowNumber}`;
    }
    if (this.trackingNumber) {
      return `/api/v1/labels/${this.trackingNumber}`;
    }
    return '';
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (
      changes['labelUrl'] ||
      changes['trackingNumber'] ||
      changes['jobId'] ||
      changes['rowNumber']
    ) {
      this.isLoading.set(true);
      this.loadError.set(null);
    }
  }

  onLoadComplete(pdf: { numPages: number }): void {
    this.isLoading.set(false);
    this.loadError.set(null);
  }

  onLoadError(error: unknown): void {
    this.isLoading.set(false);
    const message =
      error instanceof Error
        ? error.message
        : 'Could not load PDF';
    this.loadError.set(message);
  }

  handleDownload(): void {
    const url = this.resolvedUrl;
    if (!url) return;
    const link = document.createElement('a');
    link.href = url;
    link.download = this.trackingNumber
      ? `${this.trackingNumber}.pdf`
      : 'labels.pdf';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  handlePrint(): void {
    const url = this.resolvedUrl;
    if (!url) return;
    const printWindow = window.open(url, '_blank');
    if (printWindow) {
      printWindow.addEventListener('load', () => {
        printWindow.print();
      });
    }
  }
}

// frontend/src/components/LabelPreview.tsx
/**
 * LabelPreview component for in-browser PDF label viewing.
 *
 * Renders shipping labels in a modal dialog with react-pdf,
 * allowing users to preview before downloading.
 */

import * as React from 'react';
import { Document, Page, pdfjs } from 'react-pdf';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { LoadingIcon, AlertIcon, PrinterIcon, DownloadIcon } from '@/components/ui/icons';

// Configure PDF.js worker - resolves the local pdfjs-dist worker file via Vite.
// IMPORTANT: pdfjs-dist in package.json must be pinned to the exact version that
// react-pdf depends on (check react-pdf's package.json). A version mismatch causes
// "API version X does not match Worker version Y" errors at runtime.
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.mjs',
  import.meta.url
).toString();

export interface LabelPreviewProps {
  /** The UPS tracking number for the label (used for single-label view). */
  trackingNumber?: string;
  /** Job ID for per-row label access (handles non-unique tracking numbers). */
  jobId?: string;
  /** Row number within the job for per-row label access. */
  rowNumber?: number;
  /** Direct PDF URL (used for merged labels or custom sources). */
  pdfUrl?: string;
  /** Title displayed in the modal header. */
  title?: string;
  /** Whether the modal is open. */
  isOpen: boolean;
  /** Callback when modal closes. */
  onClose: () => void;
}

/** Loading state component. */
function LoadingState() {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
      <LoadingIcon className="h-8 w-8 animate-spin mb-4" />
      <p>Loading label...</p>
    </div>
  );
}

/** Error state component. */
function ErrorState({ message }: { message: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-red-600 dark:text-red-400">
      <AlertIcon className="h-8 w-8 mb-4" />
      <p className="text-sm font-medium mb-2">Failed to load label</p>
      <p className="text-xs text-muted-foreground">{message}</p>
    </div>
  );
}

/**
 * LabelPreview displays a PDF shipping label in a modal dialog.
 *
 * Features:
 * - Modal dialog with react-pdf Document and Page components
 * - Loading state while PDF loads
 * - Error state if PDF fails to load
 * - Download button in modal footer
 * - Close on backdrop click or Escape key (via Radix Dialog)
 * - Fits label to modal width
 */
export function LabelPreview({
  trackingNumber,
  jobId,
  rowNumber,
  pdfUrl: pdfUrlProp,
  title,
  isOpen,
  onClose,
}: LabelPreviewProps) {
  const [numPages, setNumPages] = React.useState<number>(0);
  const [isLoading, setIsLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [containerWidth, setContainerWidth] = React.useState<number>(500);
  const containerRef = React.useRef<HTMLDivElement>(null);

  // Resolve PDF URL: explicit pdfUrl > per-row endpoint > tracking number fallback
  // Per-row endpoint handles non-unique tracking numbers (UPS sandbox)
  const resolvedPdfUrl = pdfUrlProp
    || (jobId && rowNumber != null ? `/api/v1/jobs/${jobId}/labels/${rowNumber}` : '')
    || (trackingNumber ? `/api/v1/labels/${trackingNumber}` : '');

  // Observe container width for responsive PDF scaling
  React.useEffect(() => {
    if (!containerRef.current) return;

    const observer = new ResizeObserver((entries) => {
      for (const entry of entries) {
        // Account for padding (24px on each side)
        setContainerWidth(entry.contentRect.width);
      }
    });

    observer.observe(containerRef.current);
    return () => observer.disconnect();
  }, []);

  // Reset state when modal opens
  React.useEffect(() => {
    if (isOpen) {
      setIsLoading(true);
      setError(null);
      setNumPages(0);
    }
  }, [isOpen, trackingNumber, pdfUrlProp]);

  const handleLoadSuccess = ({ numPages }: { numPages: number }) => {
    setNumPages(numPages);
    setIsLoading(false);
    setError(null);
  };

  const handleLoadError = (err: Error) => {
    setIsLoading(false);
    setError(err.message || 'Could not load PDF');
  };

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = resolvedPdfUrl;
    link.download = trackingNumber ? `${trackingNumber}.pdf` : 'labels.pdf';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrint = () => {
    const printWindow = window.open(resolvedPdfUrl, '_blank');
    if (printWindow) {
      printWindow.addEventListener('load', () => {
        printWindow.print();
      });
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[600px] max-h-[90vh] flex flex-col">
        {/* Visually hidden header for accessibility */}
        <DialogHeader className="sr-only">
          <DialogTitle>{title || 'Label Preview'}</DialogTitle>
          <DialogDescription>Shipping label preview</DialogDescription>
        </DialogHeader>

        <div
          ref={containerRef}
          className="flex-1 overflow-y-auto min-h-0 bg-muted/30 rounded-md p-4"
        >
          {isLoading && !error && <LoadingState />}
          {error && <ErrorState message={error} />}

          <Document
            file={resolvedPdfUrl}
            onLoadSuccess={handleLoadSuccess}
            onLoadError={handleLoadError}
            loading={<LoadingState />}
            error={<ErrorState message="Failed to load PDF document" />}
            className={cn('flex flex-col items-center gap-4', isLoading && 'hidden')}
          >
            {Array.from(new Array(numPages), (_, index) => (
              <Page
                key={`page_${index + 1}`}
                pageNumber={index + 1}
                width={containerWidth - 32} // Subtract padding
                renderTextLayer={false}
                renderAnnotationLayer={false}
                className="shadow-md"
              />
            ))}
          </Document>
        </div>

        <DialogFooter className="border-t pt-4 gap-2 sm:gap-0">
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
          <Button variant="outline" onClick={handlePrint} disabled={isLoading || !!error}>
            <PrinterIcon className="h-4 w-4 mr-2" />
            Print
          </Button>
          <Button onClick={handleDownload} disabled={isLoading || !!error}>
            <DownloadIcon className="h-4 w-4 mr-2" />
            Download
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default LabelPreview;
