// frontend/src/components/command-center/ProgressDisplay.tsx
/**
 * Real-time batch execution progress display.
 *
 * Shows progress bar, success/failure stats, per-row failure details,
 * and download button on completion.
 */

import * as React from 'react';
import { useJobProgress } from '@/hooks/useJobProgress';
import { cn, formatCurrency } from '@/lib/utils';
import { getMergedLabelsUrl } from '@/lib/api';
import { DownloadIcon } from '@/components/ui/icons';

/** Per-row failure detail for callbacks. */
export interface RowFailureInfo {
  rowNumber: number;
  errorCode: string;
  errorMessage: string;
}

/** Progress data passed to completion callbacks. */
export interface ProgressData {
  total: number;
  successful: number;
  failed: number;
  totalCostCents: number;
  rowFailures: RowFailureInfo[];
}

/** Live batch execution progress with per-row failures. */
export function ProgressDisplay({ jobId, onComplete, onFailed }: {
  jobId: string;
  onComplete?: (data: ProgressData) => void;
  onFailed?: (data: ProgressData) => void;
}) {
  const { progress } = useJobProgress(jobId);
  const completeFiredRef = React.useRef(false);
  const failFiredRef = React.useRef(false);

  const percentage = progress.total > 0 ? Math.round((progress.processed / progress.total) * 100) : 0;
  const isRunning = progress.status === 'running';
  const isComplete = progress.status === 'completed';
  const isFailed = progress.status === 'failed';

  React.useEffect(() => {
    if (isComplete && !completeFiredRef.current && onComplete) {
      completeFiredRef.current = true;
      onComplete({
        total: progress.total,
        successful: progress.successful,
        failed: progress.failed,
        totalCostCents: progress.totalCostCents,
        rowFailures: progress.rowFailures,
      });
    }
  }, [isComplete, onComplete, progress]);

  React.useEffect(() => {
    if (isFailed && !failFiredRef.current && onFailed) {
      failFiredRef.current = true;
      onFailed({
        total: progress.total,
        successful: progress.successful,
        failed: progress.failed,
        totalCostCents: progress.totalCostCents,
        rowFailures: progress.rowFailures,
      });
    }
  }, [isFailed, onFailed, progress]);

  return (
    <div className={cn(
      'card-premium p-4 space-y-4',
      isRunning && 'scan-line',
      isComplete && 'border-success/30',
      isFailed && 'border-error/30'
    )}>
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-medium text-slate-200">
          {isComplete ? 'Batch Complete' : isFailed ? 'Batch Failed' : 'Processing Shipments'}
        </h3>
        <span className={cn(
          'badge',
          isComplete && 'badge-success',
          isFailed && 'badge-error',
          isRunning && 'badge-info'
        )}>
          {progress.status}
        </span>
      </div>

      {/* Progress bar */}
      <div className="space-y-2">
        <div className="progress-bar">
          <div
            className={cn('progress-bar-fill', isRunning && 'animated')}
            style={{ width: `${percentage}%` }}
          />
        </div>
        <div className="flex justify-between text-xs font-mono">
          <span className="text-slate-400">
            {progress.processed} / {progress.total} rows
          </span>
          <span className="text-slate-400">{percentage}%</span>
        </div>
      </div>

      {/* Stats */}
      <div className={cn('grid gap-2', progress.dutiesTaxesCents ? 'grid-cols-5' : 'grid-cols-4')}>
        <div className="p-2 rounded bg-slate-800/50 text-center">
          <p className="text-lg font-semibold text-slate-100">{progress.total}</p>
          <p className="text-[10px] font-mono text-slate-500">Total</p>
        </div>
        <div className="p-2 rounded bg-slate-800/50 text-center">
          <p className="text-lg font-semibold text-success">{progress.successful}</p>
          <p className="text-[10px] font-mono text-slate-500">Success</p>
        </div>
        <div className="p-2 rounded bg-slate-800/50 text-center">
          <p className="text-lg font-semibold text-error">{progress.failed}</p>
          <p className="text-[10px] font-mono text-slate-500">Failed</p>
        </div>
        <div className="p-2 rounded bg-slate-800/50 text-center">
          <p className="text-lg font-semibold text-primary">
            {formatCurrency(progress.totalCostCents)}
          </p>
          <p className="text-[10px] font-mono text-slate-500">Cost</p>
        </div>
        {progress.dutiesTaxesCents != null && progress.dutiesTaxesCents > 0 && (
          <div className="p-2 rounded bg-amber-500/10 border border-amber-500/20 text-center">
            <p className="text-lg font-semibold text-amber-400">
              {formatCurrency(progress.dutiesTaxesCents)}
            </p>
            <p className="text-[10px] font-mono text-amber-400/70">Duties</p>
          </div>
        )}
      </div>

      {/* Per-row failure details */}
      {(progress.rowFailures?.length ?? 0) > 0 && (
        <div className="space-y-1.5">
          <p className="text-[11px] font-medium text-error/90">
            {progress.rowFailures.length} row{progress.rowFailures.length !== 1 ? 's' : ''} failed:
          </p>
          <div className="max-h-[120px] overflow-y-auto scrollable space-y-1">
            {progress.rowFailures.map((f) => (
              <div key={f.rowNumber} className="p-2 rounded bg-error/10 border border-error/20 flex items-start gap-2">
                <span className="text-[10px] font-mono text-error/70 flex-shrink-0 mt-px">
                  Row {f.rowNumber}
                </span>
                <span className="text-[10px] font-mono text-error/90 break-all">
                  {f.errorMessage}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Batch-level error (when no per-row details available) */}
      {isFailed && progress.error && (progress.rowFailures?.length ?? 0) === 0 && (
        <div className="p-3 rounded-lg bg-error/10 border border-error/30">
          <p className="text-xs font-mono text-error">
            {progress.error.code}: {progress.error.message}
          </p>
        </div>
      )}

      {/* Download button if complete */}
      {isComplete && (
        <button
          onClick={() => window.open(getMergedLabelsUrl(jobId), '_blank')}
          className="w-full btn-primary py-2.5 flex items-center justify-center gap-2"
        >
          <DownloadIcon className="w-4 h-4" />
          <span>Download All Labels (PDF)</span>
        </button>
      )}
    </div>
  );
}

// shipagent-frontend/apps/chat-remote/src/app/progress-display/progress-display.component.ts
/**
 * ProgressDisplayComponent — Real-time batch execution progress display.
 *
 * Reads live progress signals from JobProgressSseService.
 * Shows progress bar, stats grid, per-row failure details, and a
 * download button when complete. Matches React's ProgressDisplay component.
 */

import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
  inject,
  effect,
  Injector,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormatCurrencyPipe, DownloadIconComponent } from '@shipagent/shared-ui';
import { ApiService } from '@shipagent/shared-api';
import { JobProgressSseService } from '../../services/job-progress-sse.service';

@Component({
  selector: 'app-progress-display',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, FormatCurrencyPipe, DownloadIconComponent],
  template: `
    <div class="card-premium p-4 space-y-4"
      [class.scan-line]="progressService.isRunning()"
      [class.border-success/30]="progressService.isComplete()"
      [class.border-error/30]="progressService.isFailed()"
    >
      <!-- Header -->
      <div class="flex items-center justify-between">
        <h3 class="text-sm font-medium text-slate-200">
          @if (progressService.isComplete()) {
            Batch Complete
          } @else if (progressService.isFailed()) {
            Batch Failed
          } @else {
            Processing Shipments
          }
        </h3>
        <span class="badge"
          [class.badge-success]="progressService.isComplete()"
          [class.badge-error]="progressService.isFailed()"
          [class.badge-info]="progressService.isRunning()"
        >
          {{ progressService.progress().status }}
        </span>
      </div>

      <!-- Progress bar -->
      <div class="space-y-2">
        <div class="progress-bar">
          <div
            class="progress-bar-fill"
            [class.animated]="progressService.isRunning()"
            [style.width.%]="progressService.percentage()"
          ></div>
        </div>
        <div class="flex justify-between text-xs font-mono">
          <span class="text-slate-400">
            {{ progressService.progress().processed }} / {{ progressService.progress().total }} shipments
          </span>
          <span class="text-slate-400">{{ progressService.percentage() }}%</span>
        </div>
      </div>

      <!-- Stats grid -->
      <div class="grid gap-2"
        [class.grid-cols-4]="!progressService.progress().dutiesTaxesCents"
        [class.grid-cols-5]="progressService.progress().dutiesTaxesCents"
      >
        <div class="p-2 rounded bg-slate-800/50 text-center">
          <p class="text-lg font-semibold text-slate-100">{{ progressService.progress().total }}</p>
          <p class="text-[10px] font-mono text-slate-500">Total</p>
        </div>
        <div class="p-2 rounded bg-slate-800/50 text-center">
          <p class="text-lg font-semibold text-success">{{ progressService.progress().successful }}</p>
          <p class="text-[10px] font-mono text-slate-500">Success</p>
        </div>
        <div class="p-2 rounded bg-slate-800/50 text-center">
          <p class="text-lg font-semibold text-error">{{ progressService.progress().failed }}</p>
          <p class="text-[10px] font-mono text-slate-500">Failed</p>
        </div>
        <div class="p-2 rounded bg-slate-800/50 text-center">
          <p class="text-lg font-semibold text-primary">
            {{ progressService.progress().totalCostCents | formatCurrency }}
          </p>
          <p class="text-[10px] font-mono text-slate-500">Cost</p>
        </div>
        @if (progressService.progress().dutiesTaxesCents != null && progressService.progress().dutiesTaxesCents! > 0) {
          <div class="p-2 rounded bg-amber-500/10 border border-amber-500/20 text-center">
            <p class="text-lg font-semibold text-amber-400">
              {{ progressService.progress().dutiesTaxesCents! | formatCurrency }}
            </p>
            <p class="text-[10px] font-mono text-amber-400/70">Duties</p>
          </div>
        }
      </div>

      <!-- Per-row failure details -->
      @if (progressService.progress().rowFailures.length > 0) {
        <div class="space-y-1.5">
          <p class="text-[11px] font-medium text-error/90">
            {{ progressService.progress().rowFailures.length }} row{{ progressService.progress().rowFailures.length !== 1 ? 's' : '' }} failed:
          </p>
          <div class="max-h-[120px] overflow-y-auto space-y-1">
            @for (failure of progressService.progress().rowFailures; track failure.rowNumber) {
              <div class="p-2 rounded bg-error/10 border border-error/20 flex items-start gap-2">
                <span class="text-[10px] font-mono text-error/70 flex-shrink-0 mt-px">
                  Row {{ failure.rowNumber }}
                </span>
                <span class="text-[10px] font-mono text-error/90 break-all">
                  {{ failure.errorMessage }}
                </span>
              </div>
            }
          </div>
        </div>
      }

      <!-- Batch-level error (when no per-row details) -->
      @if (progressService.isFailed() && progressService.progress().error && progressService.progress().rowFailures.length === 0) {
        <div class="p-3 rounded-lg bg-error/10 border border-error/30">
          <p class="text-xs font-mono text-error">
            {{ progressService.progress().error!.code }}: {{ progressService.progress().error!.message }}
          </p>
        </div>
      }

      <!-- Download button when complete -->
      @if (progressService.isComplete() && jobId) {
        <button
          type="button"
          class="w-full btn-primary py-2.5 flex items-center justify-center gap-2"
          (click)="downloadLabels()"
        >
          <sa-icon-download class="w-4 h-4" />
          <span>Download All Labels (PDF)</span>
        </button>
      }
    </div>
  `,
})
export class ProgressDisplayComponent implements OnInit, OnChanges, OnDestroy {
  @Input({ required: true }) jobId!: string;
  @Output() complete = new EventEmitter<void>();
  @Output() failed = new EventEmitter<void>();

  readonly progressService = inject(JobProgressSseService);
  private readonly apiService = inject(ApiService);
  private readonly injector = inject(Injector);

  private completeFired = false;
  private failFired = false;

  ngOnInit(): void {
    this.connectToJob();
    this.setupCompletionEffects();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['jobId'] && !changes['jobId'].isFirstChange()) {
      this.completeFired = false;
      this.failFired = false;
      this.connectToJob();
    }
  }

  ngOnDestroy(): void {
    this.progressService.disconnect();
  }

  downloadLabels(): void {
    if (this.jobId) {
      window.open(this.apiService.getMergedLabelsUrl(this.jobId), '_blank');
    }
  }

  private connectToJob(): void {
    if (this.jobId) {
      this.progressService.connectToJobProgress(this.jobId);
    }
  }

  private setupCompletionEffects(): void {
    effect(() => {
      if (this.progressService.isComplete() && !this.completeFired) {
        this.completeFired = true;
        this.complete.emit();
      }
    }, { injector: this.injector });

    effect(() => {
      if (this.progressService.isFailed() && !this.failFired) {
        this.failFired = true;
        this.failed.emit();
      }
    }, { injector: this.injector });
  }
}
