// shipagent-frontend/apps/sidebar-remote/src/app/data-source-panel/data-source-panel.component.ts
/**
 * DataSourcePanelComponent
 *
 * Main data source management panel for the sidebar.
 * Shows the connected data source status, local source controls,
 * platform source controls, write-back toggle, and reconnect card.
 * Port of React DataSourcePanel.tsx (DataSourceSection).
 */

import {
  ChangeDetectionStrategy,
  Component,
  inject,
  OnInit,
  signal,
} from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { ApiService } from '@shipagent/shared-api';
import { DataSourceStore, ConversationStore } from '@shipagent/shared-state';
import {
  HardDriveIconComponent,
  InfoIconComponent,
} from '@shipagent/shared-ui';
import { DataSourceMappersService } from './data-source-mappers.service';
import { LocalSourceComponent } from './local-source.component';
import { PlatformSourceComponent } from './platform-source.component';
import { RecentSourcesModalComponent } from '../recent-sources-modal/recent-sources-modal.component';
import type { DataSourceInfo } from '@shipagent/shared-types';

@Component({
  selector: 'sa-data-source-panel',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    HardDriveIconComponent,
    InfoIconComponent,
    LocalSourceComponent,
    PlatformSourceComponent,
    RecentSourcesModalComponent,
  ],
  template: `
    <div class="p-3 space-y-3">
      <span class="text-xs font-medium text-slate-300">Data Sources</span>

      <!-- Platform connections (Shopify, Amazon) -->
      <sa-platform-source />

      <!-- === ACTIVE LOCAL SOURCE CARD === -->
      @if (dataSourceStore.dataSource()?.status === 'connected') {
        <div
          [class]="localSourceCardClass()"
        >
          <div class="flex items-center justify-between p-2.5">
            <div class="flex items-center gap-2">
              <sa-icon-hard-drive class="w-4 h-4 text-slate-400" />
              <span class="text-xs font-medium text-slate-200">{{ localFileName() }}</span>
            </div>
            <div>
              @if (isLocalActive() && conversationStore.interactiveShipping()) {
                <span class="badge badge-neutral text-[9px]">STANDBY</span>
              } @else if (isLocalActive()) {
                <span class="badge badge-success text-[9px]">ACTIVE</span>
              } @else {
                <span class="text-[10px] font-mono text-slate-500">Available</span>
              }
            </div>
          </div>
          <div class="px-2.5 pb-2.5 flex items-center justify-between">
            <div class="flex gap-4 text-[10px] font-mono">
              <span class="text-slate-500">
                Rows: <span [class.text-green-400]="isLocalActive() && !conversationStore.interactiveShipping()" [class.text-slate-400]="!isLocalActive() || conversationStore.interactiveShipping()">{{ dataSourceStore.dataSource()?.row_count?.toLocaleString() || '...' }}</span>
              </span>
              <span class="text-slate-500">
                Cols: <span class="text-slate-300">{{ dataSourceStore.dataSource()?.column_count }}</span>
              </span>
            </div>
            <button
              class="text-[10px] font-mono text-red-400 hover:underline"
              (click)="handleDisconnect()"
            >
              Disconnect
            </button>
          </div>
          @if (isLocalActive() && conversationStore.interactiveShipping()) {
            <div class="px-2.5 pb-2 -mt-1">
              <p class="text-[10px] font-mono text-slate-500">Available in batch mode</p>
            </div>
          }
        </div>
      }

      <!-- === CACHED RECONNECT CARD === -->
      @if (!dataSourceStore.dataSource() && dataSourceStore.cachedLocalConfig()?.file_path) {
        <div class="rounded-lg border border-dashed border-slate-700 p-2.5">
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <sa-icon-hard-drive class="w-4 h-4 text-slate-500" />
              <span class="text-xs text-slate-400 truncate">
                {{ lastFileName() }}
              </span>
            </div>
            <button
              class="text-[10px] font-medium text-primary hover:underline disabled:opacity-50"
              [disabled]="isReconnecting()"
              (click)="handleReconnectLocal()"
            >
              @if (isReconnecting()) { Reconnecting... } @else { Reconnect }
            </button>
          </div>
        </div>
      }

      <!-- === WRITE-BACK TOGGLE === -->
      @if (dataSourceStore.activeSourceType() && !conversationStore.interactiveShipping()) {
        <div class="flex items-center justify-between px-3 py-2 mt-1 rounded-md bg-slate-800/50 border border-slate-800/50">
          <div class="flex items-center gap-1.5">
            <label for="write-back-toggle" class="text-[11px] text-slate-400 select-none">
              Sync tracking info
            </label>
            <div class="relative group">
              <sa-icon-info class="w-3.5 h-3.5 text-slate-500 cursor-help" />
              <div class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2 py-1.5 bg-slate-800 text-slate-100 text-[10px] rounded shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-150 w-40 text-center leading-relaxed z-50 pointer-events-none">
                Automatically updates tracking numbers on the original data source.
              </div>
            </div>
          </div>
          <!-- Minimal toggle switch -->
          <button
            id="write-back-toggle"
            role="switch"
            class="relative inline-flex h-5 w-9 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200"
            [class.bg-primary]="dataSourceStore.writeBackEnabled()"
            [class.bg-slate-700]="!dataSourceStore.writeBackEnabled()"
            [attr.aria-checked]="dataSourceStore.writeBackEnabled()"
            (click)="toggleWriteBack()"
          >
            <span
              class="pointer-events-none inline-block h-4 w-4 transform rounded-full bg-white shadow-sm ring-0 transition duration-200"
              [class.translate-x-4]="dataSourceStore.writeBackEnabled()"
              [class.translate-x-0]="!dataSourceStore.writeBackEnabled()"
            ></span>
          </button>
        </div>
      }

      <!-- === IMPORT SECTION (when no source connected) === -->
      @if (!dataSourceStore.dataSource()?.status) {
        <sa-local-source (openSavedSources)="showRecentSources.set(true)" />
      }

      <!-- Reconnect error -->
      @if (reconnectError()) {
        <p class="text-[10px] font-mono text-red-400 p-2 rounded bg-red-500/10">{{ reconnectError() }}</p>
      }
    </div>

    <!-- Recent Sources Modal -->
    <sa-recent-sources-modal
      [open]="showRecentSources()"
      (closed)="showRecentSources.set(false)"
      (reconnected)="onReconnected($event)"
    />
  `,
})
export class DataSourcePanelComponent implements OnInit {
  readonly dataSourceStore = inject(DataSourceStore);
  readonly conversationStore = inject(ConversationStore);
  private readonly apiService = inject(ApiService);
  private readonly mappers = inject(DataSourceMappersService);

  readonly showRecentSources = signal(false);
  readonly isReconnecting = signal(false);
  readonly reconnectError = signal<string | null>(null);

  ngOnInit(): void {
    this.hydrateSourceStatus();
  }

  /** Whether local source is currently active. */
  isLocalActive(): boolean {
    return this.dataSourceStore.activeSourceType() === 'local';
  }

  /** CSS class string for the local source card — varies by interactive mode. */
  localSourceCardClass(): string {
    const base = 'rounded-lg border overflow-hidden transition-colors';
    if (this.isLocalActive() && this.conversationStore.interactiveShipping()) {
      return `${base} border-l-4 border-l-slate-500 border-slate-600/30 bg-slate-800/20`;
    }
    if (this.isLocalActive()) {
      return `${base} border-l-4 border-l-primary border-primary/30 bg-primary/5`;
    }
    return `${base} border-slate-800`;
  }

  /** Display filename for the connected local source. */
  localFileName(): string {
    const ds = this.dataSourceStore.dataSource();
    if (!ds) return '';
    return this.mappers.extractFileName(ds.csv_path, ds.excel_path, ds.file_path)
      ?? ds.type.toUpperCase();
  }

  /** Filename from cached config for reconnect card. */
  lastFileName(): string {
    const path = this.dataSourceStore.cachedLocalConfig()?.file_path ?? '';
    return path.split('/').pop() ?? path;
  }

  /** Toggle write-back tracking info preference. */
  toggleWriteBack(): void {
    this.dataSourceStore.setWriteBackEnabled(!this.dataSourceStore.writeBackEnabled());
  }

  /** Disconnect the current data source. */
  async handleDisconnect(): Promise<void> {
    try {
      await firstValueFrom(this.apiService.disconnectDataSource());
    } catch {
      // Ignore errors — clear local state regardless
    }
    this.dataSourceStore.clearDataSource();
    this.dataSourceStore.setCachedLocalConfig(null);
  }

  /** Reconnect the previously used local source via saved-sources API. */
  async handleReconnectLocal(): Promise<void> {
    const config = this.dataSourceStore.cachedLocalConfig();
    if (!config?.file_path) return;

    this.isReconnecting.set(true);
    this.reconnectError.set(null);

    try {
      const saved = await firstValueFrom(this.apiService.getSavedSources());
      const fileName = config.file_path.split('/').pop()?.toLowerCase();
      const match = saved.sources.find(
        (s) => s.name.toLowerCase() === fileName,
      );

      if (!match) {
        this.reconnectError.set('Source not found. Please import the file again.');
        return;
      }

      const result = await firstValueFrom(this.apiService.reconnectSavedSource(match.id));
      const source: DataSourceInfo = {
        type: match.source_type,
        status: 'connected',
        row_count: result.row_count,
        column_count: result.column_count,
        connected_at: new Date().toISOString(),
        csv_path: match.source_type === 'csv' ? (match.file_path ?? undefined) : undefined,
        excel_path: match.source_type === 'excel' ? (match.file_path ?? undefined) : undefined,
        file_path: match.file_path ?? undefined,
      };
      this.dataSourceStore.setDataSource(source);
      this.dataSourceStore.setActiveSourceType('local');
    } catch (err) {
      this.reconnectError.set(err instanceof Error ? err.message : 'Reconnect failed');
    } finally {
      this.isReconnecting.set(false);
    }
  }

  /** Handle reconnected source from modal. */
  onReconnected(source: DataSourceInfo): void {
    this.dataSourceStore.setDataSource(source);
    this.dataSourceStore.setActiveSourceType('local');
    this.showRecentSources.set(false);
  }

  /** Hydrate source status from backend on component init. */
  private async hydrateSourceStatus(): Promise<void> {
    try {
      const status = await firstValueFrom(this.apiService.getDataSourceStatus());
      if (!status.connected) return;

      const sourceType = String(status.source_type ?? '').toLowerCase();
      const KNOWN_TYPES = new Set(['csv', 'excel', 'json', 'xml', 'fixed_width', 'edi', 'database']);

      if (KNOWN_TYPES.has(sourceType)) {
        const localType = sourceType as DataSourceInfo['type'];
        const source: DataSourceInfo = {
          type: localType,
          status: 'connected',
          row_count: status.row_count,
          column_count: status.columns?.length,
          columns: status.columns ? this.mappers.mapSchemaColumns(status.columns) : undefined,
          connected_at: new Date().toISOString(),
          csv_path: localType === 'csv' ? status.file_path ?? undefined : undefined,
          excel_path: localType === 'excel' ? status.file_path ?? undefined : undefined,
          file_path: (KNOWN_TYPES.has(localType) && localType !== 'csv' && localType !== 'excel' && localType !== 'database')
            ? status.file_path ?? undefined
            : undefined,
        };
        this.dataSourceStore.setDataSource(source);
        this.dataSourceStore.setActiveSourceType('local');
      } else if (sourceType === 'shopify') {
        this.dataSourceStore.setActiveSourceType('shopify');
      } else if (sourceType === 'amazon') {
        this.dataSourceStore.setActiveSourceType('amazon');
      }
    } catch {
      // Best-effort hydration — keep current UI state on failure
    }
  }
}

// frontend/src/components/sidebar/DataSourcePanel.tsx
/**
 * Data source management panel for the sidebar.
 *
 * Handles local file import (CSV/Excel), database connections,
 * Shopify platform integration, and source switching.
 */

import * as React from 'react';
import { useAppState } from '@/hooks/useAppState';
import { useExternalSources } from '@/hooks/useExternalSources';
import { cn } from '@/lib/utils';
import {
  disconnectDataSource,
  importDataSource,
  uploadDataSource,
  getSavedDataSources,
  reconnectSavedSource,
  getDataSourceStatus,
} from '@/lib/api';
import type { DataSourceInfo, DataSourceType } from '@/types/api';
import { RecentSourcesModal } from '@/components/RecentSourcesModal';
import { toDataSourceColumns } from '@/components/sidebar/dataSourceMappers';
import { HardDriveIcon, InfoIcon } from '@/components/ui/icons';
import { ShopifyIcon } from '@/components/ui/brand-icons';
import { Switch } from '@/components/ui/switch';

/** Extracts a display filename from a DataSourceInfo. */
export function extractFileName(ds: DataSourceInfo): string | null {
  const path = ds.csv_path || ds.excel_path || ds.file_path;
  if (!path) return null;
  const segments = path.split('/');
  return segments[segments.length - 1] || null;
}

// Data Source Section - Unified view with radio-card active/inactive pattern
export function DataSourceSection() {
  const {
    dataSource, setDataSource,
    activeSourceType, setActiveSourceType,
    setActiveSourceInfo,
    cachedLocalConfig, setCachedLocalConfig,
    interactiveShipping,
    writeBackEnabled, setWriteBackEnabled,
    setPendingChatMessage,
  } = useAppState();
  const { state: externalState } = useExternalSources();
  const {
    providerConnections,
    setSettingsFlyoutOpen,
  } = useAppState();
  const [isConnecting, setIsConnecting] = React.useState(false);
  const [showDbForm, setShowDbForm] = React.useState(false);
  const [dbConnectionString, setDbConnectionString] = React.useState('');
  const [backendSourceType, setBackendSourceType] = React.useState<string | null>(null);

  // Shopify availability derived from provider connections (server-side runtime_usable)
  const shopifyConnection = providerConnections.find(
    (c) => c.provider === 'shopify' && c.runtime_usable
  );
  const shopifyAvailable = !!shopifyConnection;

  // Also check env-based Shopify for backward compatibility during migration
  const shopifyEnvStatus = externalState.shopifyEnvStatus;
  const isCheckingShopifyEnv = externalState.isCheckingEnv;
  const shopifyEnvConnected = shopifyEnvStatus?.valid === true;
  const shopifyStoreName = shopifyConnection?.display_name
    || shopifyEnvStatus?.store_name
    || shopifyEnvStatus?.store_url;

  // Recent sources modal
  const [showRecentSources, setShowRecentSources] = React.useState(false);

  // File picker ref and state
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const [importError, setImportError] = React.useState<string | null>(null);

  React.useEffect(() => {
    let isCancelled = false;

    const hydrateSourceStatus = async () => {
      try {
        const status = await getDataSourceStatus();
        if (isCancelled) return;

        if (!status.connected) {
          setBackendSourceType(null);
          return;
        }

        const sourceType = String(status.source_type || '').toLowerCase();
        setBackendSourceType(sourceType || null);

        const KNOWN_TYPES = new Set<string>(['csv', 'excel', 'json', 'xml', 'fixed_width', 'edi', 'database']);
        if (KNOWN_TYPES.has(sourceType)) {
          const localType = sourceType as DataSourceType;
          const path = status.file_path || undefined;
          setDataSource({
            type: localType,
            status: 'connected',
            row_count: status.row_count,
            column_count: status.columns?.length,
            columns: status.columns ? toDataSourceColumns(status.columns) : undefined,
            connected_at: new Date().toISOString(),
            csv_path: localType === 'csv' ? path : undefined,
            excel_path: localType === 'excel' ? path : undefined,
            file_path: KNOWN_TYPES.has(localType) && localType !== 'csv' && localType !== 'excel' && localType !== 'database' ? path : undefined,
          });
        }
      } catch {
        // Best-effort hydration; keep current UI state on failure.
      }
    };

    void hydrateSourceStatus();
    return () => {
      isCancelled = true;
    };
  }, [setDataSource]);

  // --- Derive active source from existing state ---
  React.useEffect(() => {
    if (dataSource?.status === 'connected') {
      setActiveSourceType('local');
      setActiveSourceInfo({
        type: 'local',
        label: extractFileName(dataSource) || dataSource.type.toUpperCase(),
        detail: `${dataSource.row_count?.toLocaleString() ?? '?'} rows`,
        sourceKind: dataSource.type === 'database' ? 'database' : 'file',
      });
    } else if (backendSourceType === 'shopify' || (!backendSourceType && (shopifyAvailable || shopifyEnvConnected))) {
      setActiveSourceType('shopify');
      setActiveSourceInfo({
        type: 'shopify',
        label: 'Shopify',
        detail: shopifyStoreName || 'Connected',
        sourceKind: 'shopify',
      });
    } else {
      setActiveSourceType(null);
      setActiveSourceInfo(null);
    }
  }, [
    dataSource,
    backendSourceType,
    shopifyAvailable,
    shopifyEnvConnected,
    shopifyStoreName,
    setActiveSourceType,
    setActiveSourceInfo,
  ]);

  // --- Source switching handlers ---

  /** Switch to Shopify: disconnect local source so backend routes to Shopify. */
  const handleSwitchToShopify = async () => {
    if (dataSource) {
      setCachedLocalConfig({
        type: dataSource.type as 'csv' | 'excel' | 'database',
        file_path: dataSource.csv_path || dataSource.excel_path,
      });
    }
    try { await disconnectDataSource(); } catch { /* best-effort */ }
    setDataSource(null);
    setBackendSourceType(null);
    // useEffect will set Shopify as active
  };

  /** Open native file picker for CSV or Excel. */
  const openFilePicker = (accept: string) => {
    setImportError(null);
    if (fileInputRef.current) {
      fileInputRef.current.accept = accept;
      fileInputRef.current.value = '';
      fileInputRef.current.click();
    }
  };

  /** Handle file selection from native file picker — uploads to backend. */
  const handleFileSelected = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const ext = (file.name.split('.').pop() || '').toLowerCase();
    const EXCEL_EXTS = new Set(['xlsx', 'xls']);
    // Map to a broad category for local state — backend handles format routing
    const fileType: 'csv' | 'excel' = EXCEL_EXTS.has(ext) ? 'excel' : 'csv';

    setIsConnecting(true);
    setImportError(null);
    try {
      const result = await uploadDataSource(file);

      if (result.status === 'error') {
        setImportError(result.error || 'Import failed');
        return;
      }

      // Fixed-width files need agent-driven column setup — route to chat
      if (result.status === 'pending_agent_setup' && result.file_path) {
        setPendingChatMessage(
          `I uploaded ${file.name} as a fixed-width file (${result.file_path}). ` +
          `Please help me define the column layout.`
        );
        return;
      }

      const source: DataSourceInfo = {
        type: fileType,
        status: 'connected' as const,
        row_count: result.row_count,
        column_count: result.columns.length,
        columns: toDataSourceColumns(result.columns),
        connected_at: new Date().toISOString(),
        csv_path: fileType === 'csv' ? file.name : undefined,
        excel_path: fileType === 'excel' ? file.name : undefined,
      };
      setDataSource(source);
      setBackendSourceType(result.source_type || fileType);
      setCachedLocalConfig({ type: fileType, file_path: file.name });
    } catch (err) {
      setImportError(err instanceof Error ? err.message : 'Import failed');
    } finally {
      setIsConnecting(false);
    }
  };

  /** Reconnect a previously used local source via the saved-sources API. */
  const handleReconnectLocal = async () => {
    if (!cachedLocalConfig?.file_path) return;

    setIsConnecting(true);
    setImportError(null);
    try {
      // Look up the saved source by matching file name
      const saved = await getSavedDataSources();
      const fileName = cachedLocalConfig.file_path.split('/').pop()?.toLowerCase();
      const match = saved.sources.find((s) =>
        s.name.toLowerCase() === fileName
      );
      if (!match) {
        // Fallback: open file picker if saved source not found
        const accept = cachedLocalConfig.type === 'csv' ? '.csv' : '.xlsx,.xls';
        openFilePicker(accept);
        return;
      }

      const result = await reconnectSavedSource(match.id);
      const source: DataSourceInfo = {
        type: match.source_type,
        status: 'connected' as const,
        row_count: result.row_count,
        column_count: result.column_count,
        connected_at: new Date().toISOString(),
        csv_path: match.source_type === 'csv' ? match.file_path ?? undefined : undefined,
        excel_path: match.source_type === 'excel' ? match.file_path ?? undefined : undefined,
        file_path: match.file_path ?? undefined,
      };
      setDataSource(source);
      setBackendSourceType(match.source_type);
    } catch (err) {
      setImportError(err instanceof Error ? err.message : 'Reconnect failed');
    } finally {
      setIsConnecting(false);
    }
  };

  // Database connection handler — calls backend import API
  const handleDbConnect = async () => {
    if (!dbConnectionString.trim()) return;

    setIsConnecting(true);
    setImportError(null);
    try {
      const result = await importDataSource({
        type: 'database',
        connection_string: dbConnectionString.trim(),
        query: 'SELECT * FROM shipments',
      });

      if (result.status === 'error') {
        setImportError(result.error || 'Connection failed');
        return;
      }

      const source: DataSourceInfo = {
        type: 'database',
        status: 'connected' as const,
        row_count: result.row_count,
        column_count: result.columns.length,
        columns: toDataSourceColumns(result.columns),
        connected_at: new Date().toISOString(),
      };
      setDataSource(source);
      setBackendSourceType('database');
      setCachedLocalConfig({ type: 'database' });
      setDbConnectionString('');
      setShowDbForm(false);
    } catch (err) {
      setImportError(err instanceof Error ? err.message : 'Connection failed');
    } finally {
      setIsConnecting(false);
    }
  };

  const handleDisconnect = async () => {
    try {
      await disconnectDataSource();
    } catch {
      // Ignore errors - clear local state anyway
    }
    setDataSource(null);
    setBackendSourceType(null);
    setCachedLocalConfig(null);
    setImportError(null);
  };

  // Derived state for card rendering
  const isLocalActive = activeSourceType === 'local';
  const isShopifyActive = activeSourceType === 'shopify';
  const localFileName = dataSource ? (extractFileName(dataSource) || dataSource.type.toUpperCase()) : null;

  return (
    <div className="p-3 space-y-3">
      <span className="text-xs font-medium text-slate-300">Data Sources</span>

      {/* === SHOPIFY CARD === */}
      {(shopifyAvailable || shopifyEnvConnected) ? (
        <div className={cn(
          'rounded-lg border overflow-hidden transition-colors',
          isShopifyActive && interactiveShipping
            ? 'border-l-4 border-l-slate-500 border-slate-600/30 bg-slate-800/20'
            : isShopifyActive
              ? 'border-l-4 border-l-[#5BBF3D] border-[#5BBF3D]/30 bg-[#5BBF3D]/5'
              : 'border-slate-800'
        )}>
          <div className="flex items-center justify-between p-2.5 bg-slate-800/30">
            <div className="flex items-center gap-2">
              <ShopifyIcon className="w-5 h-5 text-[#5BBF3D]" />
              <span className="text-xs font-medium text-slate-200">Shopify</span>
            </div>
            <div className="flex items-center gap-2">
              {isCheckingShopifyEnv ? (
                <span className="text-[10px] font-mono text-slate-500">Checking...</span>
              ) : isShopifyActive && interactiveShipping ? (
                <span className="badge badge-neutral text-[9px]">STANDBY</span>
              ) : isShopifyActive ? (
                <span className="badge badge-success text-[9px]">ACTIVE</span>
              ) : (
                <span className="flex items-center gap-1.5">
                  <span className="w-1.5 h-1.5 rounded-full bg-slate-500" />
                  <span className="text-[10px] font-mono text-slate-500">Available</span>
                </span>
              )}
            </div>
          </div>

          {/* Active Shopify info */}
          {isShopifyActive && (
            <div className={cn('p-2.5 border-t', interactiveShipping ? 'border-slate-700' : 'border-[#5BBF3D]/20')}>
              <p className="text-xs text-slate-300">
                {shopifyStoreName}
              </p>
              <p className="text-[10px] font-mono text-slate-500 mt-0.5">
                {interactiveShipping ? 'Available in batch mode' : 'Connected'}
              </p>
            </div>
          )}

          {/* Shopify available but not active — show "Use Shopify" button */}
          {!isShopifyActive && (
            <div className="p-2.5 border-t border-slate-800">
              <p className="text-[10px] text-slate-500 mb-2">
                {shopifyStoreName}
              </p>
              <button
                onClick={handleSwitchToShopify}
                className="w-full py-1.5 text-xs font-medium rounded border border-[#5BBF3D]/40 text-[#5BBF3D] hover:bg-[#5BBF3D]/10 transition-colors"
              >
                Use Shopify
              </button>
            </div>
          )}
        </div>
      ) : (
        /* Not configured — direct to Settings */
        <div className="rounded-lg border border-slate-800 overflow-hidden">
          <div className="flex items-center justify-between p-2.5 bg-slate-800/30">
            <div className="flex items-center gap-2">
              <ShopifyIcon className="w-5 h-5 text-[#5BBF3D]/50" />
              <span className="text-xs font-medium text-slate-400">Shopify</span>
            </div>
            <span className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-slate-600" />
              <span className="text-[10px] font-mono text-slate-500">Not configured</span>
            </span>
          </div>
          <div className="p-2.5 border-t border-slate-800">
            <button
              onClick={() => setSettingsFlyoutOpen(true)}
              className="text-[10px] font-medium text-[#96BF48] hover:underline"
            >
              Connect Shopify in Settings →
            </button>
          </div>
        </div>
      )}

      {/* === LOCAL DATA SOURCE CARD === */}
      {dataSource?.status === 'connected' && (
        <div className={cn(
          'rounded-lg border overflow-hidden transition-colors',
          isLocalActive && interactiveShipping
            ? 'border-l-4 border-l-slate-500 border-slate-600/30 bg-slate-800/20'
            : isLocalActive
              ? 'border-l-4 border-l-primary border-primary/30 bg-primary/5'
              : 'border-slate-800'
        )}>
          <div className="flex items-center justify-between p-2.5">
            <div className="flex items-center gap-2">
              <HardDriveIcon className="w-4 h-4 text-slate-400" />
              <span className="text-xs font-medium text-slate-200">{localFileName}</span>
            </div>
            <div className="flex items-center gap-2">
              {isLocalActive && interactiveShipping ? (
                <span className="badge badge-neutral text-[9px]">STANDBY</span>
              ) : isLocalActive ? (
                <span className="badge badge-success text-[9px]">ACTIVE</span>
              ) : (
                <span className="text-[10px] font-mono text-slate-500">Available</span>
              )}
            </div>
          </div>
          <div className="px-2.5 pb-2.5 flex items-center justify-between">
            <div className="flex gap-4 text-[10px] font-mono">
              <span className="text-slate-500">
                Rows: <span className={isLocalActive && !interactiveShipping ? 'text-success' : 'text-slate-400'}>{dataSource.row_count?.toLocaleString() || '...'}</span>
              </span>
              <span className="text-slate-500">
                Cols: <span className="text-slate-300">{dataSource.column_count}</span>
              </span>
            </div>
            <button
              onClick={handleDisconnect}
              className="text-[10px] font-mono text-error hover:underline"
            >
              Disconnect
            </button>
          </div>
          {isLocalActive && interactiveShipping && (
            <div className="px-2.5 pb-2 -mt-1">
              <p className="text-[10px] font-mono text-slate-500">Available in batch mode</p>
            </div>
          )}
        </div>
      )}

      {/* === CACHED RECONNECT CARD === */}
      {!dataSource && cachedLocalConfig?.file_path && (
        <div className="rounded-lg border border-dashed border-slate-700 p-2.5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <HardDriveIcon className="w-4 h-4 text-slate-500" />
              <span className="text-xs text-slate-400 truncate">
                {cachedLocalConfig.file_path.split('/').pop()}
              </span>
            </div>
            <button
              onClick={handleReconnectLocal}
              disabled={isConnecting}
              className="text-[10px] font-medium text-primary hover:underline disabled:opacity-50"
            >
              {isConnecting ? 'Reconnecting...' : 'Reconnect'}
            </button>
          </div>
        </div>
      )}

      {/* === WRITE-BACK TOGGLE === */}
      {activeSourceType && !interactiveShipping && (
        <div className="flex items-center justify-between px-3 py-2 mt-1 rounded-md bg-card/50 border border-slate-800/50">
          <div className="flex items-center gap-1.5">
            <label
              htmlFor="write-back-toggle"
              className="text-[11px] text-muted-foreground select-none"
            >
              Sync tracking info
            </label>
            <div className="relative group">
              <InfoIcon className="w-3.5 h-3.5 text-slate-500 cursor-help" />
              <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2 py-1.5 bg-slate-800 text-slate-100 text-[10px] rounded shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-150 w-40 text-center leading-relaxed z-50">
                Automatically updates tracking numbers on the original data source.
              </div>
            </div>
          </div>
          <Switch
            id="write-back-toggle"
            checked={writeBackEnabled}
            onCheckedChange={setWriteBackEnabled}
          />
        </div>
      )}

      {/* Hidden file input for native file picker */}
      <input
        ref={fileInputRef}
        type="file"
        className="hidden"
        onChange={handleFileSelected}
      />

      {/* === IMPORT BUTTONS === */}
      {!dataSource?.status && (
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <HardDriveIcon className="w-3.5 h-3.5 text-slate-500" />
            <span className="text-[10px] font-mono text-slate-500 uppercase tracking-wider">Import Data Source</span>
          </div>

          <div className="flex gap-2">
            <button
              onClick={() => { setShowDbForm(false); openFilePicker('.csv,.tsv,.txt,.ssv,.dat,.xlsx,.xls,.json,.xml,.edi,.x12,.fwf'); }}
              disabled={isConnecting}
              className="flex-1 py-2 px-3 rounded-lg border border-slate-700 bg-slate-800/50 hover:bg-slate-800 hover:border-slate-600 text-slate-300 transition-colors text-xs font-medium disabled:opacity-50"
            >
              Import File
            </button>
            <button
              onClick={() => setShowDbForm(!showDbForm)}
              disabled={isConnecting}
              className={cn(
                'flex-1 py-2 px-3 rounded-lg border transition-colors text-xs font-medium disabled:opacity-50',
                showDbForm
                  ? 'border-primary/50 bg-primary/10 text-primary'
                  : 'border-slate-700 bg-slate-800/50 hover:bg-slate-800 hover:border-slate-600 text-slate-300'
              )}
            >
              Database
            </button>
          </div>
          <p className="text-[10px] text-slate-500 mt-0.5">CSV, TSV, Excel, JSON, XML, EDI, and more</p>

          <button
            onClick={() => setShowRecentSources(true)}
            className="w-full py-1.5 text-[11px] font-medium rounded-md border border-slate-700 bg-slate-800/50 hover:bg-slate-800 hover:border-slate-600 text-slate-300 transition-colors"
          >
            Saved Sources
          </button>

          {/* Database connection form */}
          {showDbForm && (
            <div className="space-y-2 pt-1">
              <input
                type="text"
                value={dbConnectionString}
                onChange={(e) => setDbConnectionString(e.target.value)}
                placeholder="postgresql://user:pass@host:5432/db"
                className="w-full px-2.5 py-1.5 text-xs font-mono rounded bg-void-900 border border-slate-700 text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-primary"
              />
              <button
                onClick={handleDbConnect}
                disabled={!dbConnectionString.trim() || isConnecting}
                className="w-full btn-primary py-1.5 text-xs font-medium disabled:opacity-50"
              >
                {isConnecting ? 'Connecting...' : 'Connect'}
              </button>
            </div>
          )}

          {/* Error display */}
          {importError && (
            <p className="text-[10px] font-mono text-error p-2 rounded bg-error/10">{importError}</p>
          )}

          {isConnecting && !importError && (
            <p className="text-[10px] font-mono text-slate-500 text-center">Importing...</p>
          )}
        </div>
      )}

      {/* Recent Sources Modal */}
      <RecentSourcesModal
        open={showRecentSources}
        onClose={() => setShowRecentSources(false)}
        onReconnected={(info) => {
          setDataSource(info);
          setShowRecentSources(false);
        }}
      />
    </div>
  );
}
