// frontend/src/components/settings/ConnectionsSection.tsx
/**
 * ConnectionsSection - Settings accordion section for provider connections.
 *
 * Renders ProviderCards for UPS and Shopify with their credential forms.
 * Consumes provider connection state from useAppState.
 */

import * as React from 'react';
import { ChevronDown, Key, Plug } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useAppState } from '@/hooks/useAppState';
import { deleteProviderConnection, disconnectProvider, updateSettings } from '@/lib/api';
import { ProviderCard } from './ProviderCard';
import { UPSConnectForm } from './UPSConnectForm';
import { ShopifyConnectForm } from './ShopifyConnectForm';
import { AmazonConnectForm } from './AmazonConnectForm';
import { AnthropicKeyForm } from './AnthropicKeyForm';
import { ShopifyIcon, AmazonIcon } from '@/components/ui/brand-icons';

/** Simple inline UPS shield icon. */
function UPSIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
    </svg>
  );
}

interface ConnectionsSectionProps {
  isOpen: boolean;
  onToggle: () => void;
}

export function ConnectionsSection({ isOpen, onToggle }: ConnectionsSectionProps) {
  const {
    providerConnections,
    providerConnectionsLoading,
    refreshProviderConnections,
    credentialStatus,
    refreshCredentialStatus,
    appSettings,
    refreshAppSettings,
  } = useAppState();

  const [openProvider, setOpenProvider] = React.useState<string | null>(null);
  const [envSwitching, setEnvSwitching] = React.useState(false);

  const upsConnections = providerConnections.filter((c) => c.provider === 'ups');
  const shopifyConnections = providerConnections.filter((c) => c.provider === 'shopify');
  const amazonConnections = providerConnections.filter((c) => c.provider === 'amazon');

  const handleDelete = async (connectionKey: string) => {
    await deleteProviderConnection(connectionKey);
    refreshProviderConnections();
  };

  const handleDisconnect = async (connectionKey: string) => {
    await disconnectProvider(connectionKey);
    refreshProviderConnections();
  };

  const toggleProvider = (provider: string) => {
    setOpenProvider(openProvider === provider ? null : provider);
  };

  const activeUpsEnv = appSettings?.ups_environment as 'test' | 'production' | null;

  const handleEnvSwitch = async (env: 'test' | 'production') => {
    if (env === activeUpsEnv || envSwitching) return;
    setEnvSwitching(true);
    try {
      await updateSettings({ ups_environment: env });
      await refreshAppSettings();
    } finally {
      setEnvSwitching(false);
    }
  };

  const totalConfigured =
    providerConnections.filter((c) => c.status !== 'disconnected').length +
    (credentialStatus?.anthropic_api_key ? 1 : 0);

  return (
    <div className="settings-section">
      <button
        className="settings-section-header"
        onClick={onToggle}
        aria-expanded={isOpen}
      >
        <div className="flex items-center gap-2">
          <Plug className="h-4 w-4 text-muted-foreground" />
          <span className="font-medium text-foreground">Connections</span>
          {totalConfigured > 0 && (
            <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-success/15 text-success border border-success/30">
              {totalConfigured} active
            </span>
          )}
          {providerConnectionsLoading && (
            <span className="block w-3 h-3 border-2 border-muted-foreground border-t-transparent rounded-full animate-spin" />
          )}
        </div>
        <ChevronDown
          className={cn(
            'h-4 w-4 text-muted-foreground transition-transform',
            isOpen && 'rotate-180'
          )}
        />
      </button>

      {isOpen && (
        <div className="settings-section-content space-y-2">
          {/* Anthropic API Key */}
          <div className="rounded-lg border border-border overflow-hidden">
            <button
              className="w-full flex items-center justify-between px-3 py-2.5 hover:bg-muted/30 transition-colors"
              onClick={() => toggleProvider('anthropic')}
            >
              <div className="flex items-center gap-2">
                <Key className="h-4 w-4 text-[#D97706]" />
                <span className="text-xs font-medium text-foreground">Anthropic</span>
                {credentialStatus?.anthropic_api_key ? (
                  <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-success/15 text-success border border-success/30">
                    Configured
                  </span>
                ) : (
                  <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-warning/15 text-warning border border-warning/30">
                    Not configured
                  </span>
                )}
              </div>
              <ChevronDown
                className={cn(
                  'h-3.5 w-3.5 text-muted-foreground transition-transform',
                  openProvider === 'anthropic' && 'rotate-180'
                )}
              />
            </button>
            {openProvider === 'anthropic' && (
              <div className="px-3 pb-3 border-t border-border">
                <AnthropicKeyForm onSaved={refreshCredentialStatus} />
              </div>
            )}
          </div>

          {/* UPS Provider */}
          <ProviderCard
            providerName="UPS"
            icon={<UPSIcon className="h-4 w-4 text-[#FFB500]" />}
            connections={upsConnections}
            isOpen={openProvider === 'ups'}
            onToggle={() => toggleProvider('ups')}
            onDelete={handleDelete}
            onDisconnect={handleDisconnect}
            onValidated={refreshProviderConnections}
            activeEnvironment={activeUpsEnv}
          >
            {/* Active environment toggle — same credentials work for both envs */}
            {upsConnections.some((c) => c.status === 'connected') && (
              <div className="space-y-1.5">
                <label className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
                  Active Environment
                </label>
                <div className="flex gap-1.5">
                  {(['test', 'production'] as const).map((env) => {
                    const isActive = activeUpsEnv === env || (!activeUpsEnv && env === 'production');
                    return (
                      <button
                        key={env}
                        onClick={() => handleEnvSwitch(env)}
                        disabled={envSwitching}
                        className={cn(
                          'flex-1 text-xs py-1.5 px-2 rounded-md border transition-colors',
                          isActive
                            ? env === 'production'
                              ? 'bg-success/10 border-success/40 text-success font-medium'
                              : 'bg-info/10 border-info/40 text-info font-medium'
                            : 'border-border text-muted-foreground hover:bg-muted/50',
                          envSwitching && 'opacity-50 cursor-not-allowed'
                        )}
                      >
                        {env === 'test' ? 'Test (CIE)' : 'Production'}
                        {isActive && (
                          <span className="ml-1 text-[9px]">
                            {envSwitching ? '...' : '(active)'}
                          </span>
                        )}
                      </button>
                    );
                  })}
                </div>
                <p className="text-[10px] text-muted-foreground">
                  Same credentials, different API endpoints. New conversations use the selected environment.
                </p>
              </div>
            )}
            <UPSConnectForm
              existingConnections={upsConnections}
              onSaved={refreshProviderConnections}
            />
          </ProviderCard>

          {/* Shopify Provider */}
          <ProviderCard
            providerName="Shopify"
            icon={<ShopifyIcon className="h-4 w-4 text-[#5BBF3D]" />}
            connections={shopifyConnections}
            isOpen={openProvider === 'shopify'}
            onToggle={() => toggleProvider('shopify')}
            onDelete={handleDelete}
            onDisconnect={handleDisconnect}
            onValidated={refreshProviderConnections}
          >
            <ShopifyConnectForm
              existingConnection={shopifyConnections[0] ?? null}
              onSaved={refreshProviderConnections}
            />
          </ProviderCard>

          {/* Amazon Provider */}
          <ProviderCard
            providerName="Amazon"
            icon={<AmazonIcon className="h-4 w-4 text-[#FF9900]" />}
            connections={amazonConnections}
            isOpen={openProvider === 'amazon'}
            onToggle={() => toggleProvider('amazon')}
            onDelete={handleDelete}
            onDisconnect={handleDisconnect}
            onValidated={refreshProviderConnections}
          >
            <AmazonConnectForm
              existingConnection={amazonConnections[0] ?? null}
              onSaved={refreshProviderConnections}
            />
          </ProviderCard>
        </div>
      )}
    </div>
  );
}

export default ConnectionsSection;

// shipagent-frontend/apps/settings-remote/src/app/connections-section/connections-section.component.ts
/**
 * ConnectionsSectionComponent — Settings accordion section for provider connections.
 *
 * Port of ConnectionsSection.tsx React component.
 * Renders ProviderCard for Anthropic, UPS, Shopify, Amazon with credential forms.
 * Reads credential and connection state from SettingsStore and PlatformsStore.
 */

import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnInit,
  Output,
  EventEmitter,
  inject,
  signal,
  computed,
} from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { ApiService } from '@shipagent/shared-api';
import { SettingsStore, PlatformsStore } from '@shipagent/shared-state';
import { PlatformsService } from '../../services/platforms.service';
import { ProviderCardComponent } from './provider-card.component';
import { AnthropicKeyFormComponent } from './anthropic-key-form.component';
import { ShopifyConnectFormComponent } from './shopify-connect-form.component';
import { AmazonConnectFormComponent } from './amazon-connect-form.component';
import { UpsConnectFormComponent } from './ups-connect-form.component';
import type { ProviderConnectionInfo } from '@shipagent/shared-types';

@Component({
  selector: 'app-connections-section',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ProviderCardComponent,
    AnthropicKeyFormComponent,
    ShopifyConnectFormComponent,
    AmazonConnectFormComponent,
    UpsConnectFormComponent,
  ],
  template: `
    <div class="settings-section">
      <!-- Section header -->
      <button
        class="settings-section-header"
        (click)="onToggle.emit()"
        [attr.aria-expanded]="isOpen"
      >
        <div class="flex items-center gap-2">
          <!-- Plug icon -->
          <svg class="h-4 w-4 text-muted-foreground" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M18 6L6 18"></path><path d="M6 6l12 12"></path>
          </svg>
          <span class="font-medium text-foreground">Connections</span>
          @if (totalConfigured() > 0) {
            <span class="text-[10px] px-1.5 py-0.5 rounded-full bg-success/15 text-success border border-success/30">
              {{ totalConfigured() }} active
            </span>
          }
          @if (connectionsLoading()) {
            <span class="block w-3 h-3 border-2 border-muted-foreground border-t-transparent rounded-full animate-spin"></span>
          }
        </div>
        <!-- Chevron -->
        <svg
          class="h-4 w-4 text-muted-foreground transition-transform"
          [class.rotate-180]="isOpen"
          viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
          stroke-linecap="round" stroke-linejoin="round"
        >
          <polyline points="6 9 12 15 18 9"></polyline>
        </svg>
      </button>

      @if (isOpen) {
        <div class="settings-section-content space-y-2">

          <!-- Anthropic API Key -->
          <div class="rounded-lg border border-border overflow-hidden">
            <button
              class="w-full flex items-center justify-between px-3 py-2.5 hover:bg-muted/30 transition-colors"
              (click)="toggleProvider('anthropic')"
            >
              <div class="flex items-center gap-2">
                <!-- Key icon -->
                <svg class="h-4 w-4 text-[#D97706]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"></path>
                </svg>
                <span class="text-xs font-medium text-foreground">Anthropic</span>
                @if (credentialStatus()?.anthropic_api_key) {
                  <span class="text-[9px] px-1.5 py-0.5 rounded-full bg-success/15 text-success border border-success/30">
                    Configured
                  </span>
                } @else {
                  <span class="text-[9px] px-1.5 py-0.5 rounded-full bg-warning/15 text-warning border border-warning/30">
                    Not configured
                  </span>
                }
              </div>
              <svg
                class="h-3.5 w-3.5 text-muted-foreground transition-transform"
                [class.rotate-180]="openProvider() === 'anthropic'"
                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                stroke-linecap="round" stroke-linejoin="round"
              >
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </button>
            @if (openProvider() === 'anthropic') {
              <div class="px-3 pb-3 border-t border-border">
                <app-anthropic-key-form
                  (saved)="onCredentialSaved()"
                />
              </div>
            }
          </div>

          <!-- UPS Provider -->
          <app-provider-card
            providerName="UPS"
            [connections]="upsConnections()"
            [isOpen]="openProvider() === 'ups'"
            [activeEnvironment]="activeUpsEnv()"
            (onToggle)="toggleProvider('ups')"
            (onDelete)="handleDelete($event)"
            (onDisconnect)="handleDisconnect($event)"
            (onValidated)="refreshConnections()"
          >
            <ng-container slot="icon">
              <!-- UPS shield icon -->
              <svg class="h-4 w-4 text-[#FFB500]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
              </svg>
            </ng-container>

            <!-- UPS environment toggle (shown when connected) -->
            @if (upsConnections().some(isConnected)) {
              <div class="space-y-1.5">
                <label class="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
                  Active Environment
                </label>
                <div class="flex gap-1.5">
                  @for (env of ['test', 'production']; track env) {
                    <button
                      (click)="handleEnvSwitch(env)"
                      [disabled]="envSwitching()"
                      class="flex-1 text-xs py-1.5 px-2 rounded-md border transition-colors"
                      [class]="getEnvButtonClass(env)"
                    >
                      {{ env === 'test' ? 'Test (CIE)' : 'Production' }}
                      @if (isActiveEnv(env)) {
                        <span class="ml-1 text-[9px]">
                          {{ envSwitching() ? '...' : '(active)' }}
                        </span>
                      }
                    </button>
                  }
                </div>
                <p class="text-[10px] text-muted-foreground">
                  Same credentials, different API endpoints. New conversations use the selected environment.
                </p>
              </div>
            }
            <app-ups-connect-form
              [existingConnections]="upsConnections()"
              (saved)="refreshConnections()"
            />
          </app-provider-card>

          <!-- Shopify Provider -->
          <app-provider-card
            providerName="Shopify"
            [connections]="shopifyConnections()"
            [isOpen]="openProvider() === 'shopify'"
            (onToggle)="toggleProvider('shopify')"
            (onDelete)="handleDelete($event)"
            (onDisconnect)="handleDisconnect($event)"
            (onValidated)="refreshConnections()"
          >
            <ng-container slot="icon">
              <!-- Shopify icon (green S) -->
              <svg class="h-4 w-4 text-[#5BBF3D]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
              </svg>
            </ng-container>
            <app-shopify-connect-form
              [existingConnection]="shopifyConnections()[0] ?? null"
              (saved)="refreshConnections()"
            />
          </app-provider-card>

          <!-- Amazon Provider -->
          <app-provider-card
            providerName="Amazon"
            [connections]="amazonConnections()"
            [isOpen]="openProvider() === 'amazon'"
            (onToggle)="toggleProvider('amazon')"
            (onDelete)="handleDelete($event)"
            (onDisconnect)="handleDisconnect($event)"
            (onValidated)="refreshConnections()"
          >
            <ng-container slot="icon">
              <!-- Amazon icon -->
              <svg class="h-4 w-4 text-[#FF9900]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="12" y1="8" x2="12" y2="16"></line>
                <line x1="8" y1="12" x2="16" y2="12"></line>
              </svg>
            </ng-container>
            <app-amazon-connect-form
              [existingConnection]="amazonConnections()[0] ?? null"
              (saved)="refreshConnections()"
            />
          </app-provider-card>

        </div>
      }
    </div>
  `,
})
export class ConnectionsSectionComponent implements OnInit {
  private readonly apiService = inject(ApiService);
  private readonly settingsStore = inject(SettingsStore);
  private readonly platformsStore = inject(PlatformsStore);
  private readonly platformsService = inject(PlatformsService);

  @Input() isOpen = false;
  @Output() onToggle = new EventEmitter<void>();

  openProvider = signal<string | null>(null);
  connectionsLoading = signal(false);
  envSwitching = signal(false);

  // Computed from SettingsStore
  credentialStatus = this.settingsStore.credentialStatus;
  appSettings = this.settingsStore.appSettings;

  // Computed connection lists from PlatformsStore
  allConnections = computed(() => Object.values(this.platformsStore.connections()));

  upsConnections = computed(() =>
    this.allConnections().filter((c: ProviderConnectionInfo) => c.provider === 'ups'),
  );

  shopifyConnections = computed(() =>
    this.allConnections().filter((c: ProviderConnectionInfo) => c.provider === 'shopify'),
  );

  amazonConnections = computed(() =>
    this.allConnections().filter((c: ProviderConnectionInfo) => c.provider === 'amazon'),
  );

  activeUpsEnv = computed(() => {
    const settings = this.settingsStore.appSettings();
    return (settings as any)?.ups_environment as 'test' | 'production' | null ?? null;
  });

  totalConfigured = computed(() => {
    const platformsConfigured = this.allConnections().filter(
      (c: ProviderConnectionInfo) => c.status !== 'disconnected',
    ).length;
    const hasAnthropicKey = this.settingsStore.credentialStatus()?.anthropic_api_key ? 1 : 0;
    return platformsConfigured + hasAnthropicKey;
  });

  ngOnInit(): void {
    this.loadInitialState();
  }

  private async loadInitialState(): Promise<void> {
    this.connectionsLoading.set(true);
    try {
      await Promise.all([
        this.refreshConnections(),
        firstValueFrom(this.apiService.getCredentialStatus()).then((status) =>
          this.settingsStore.setCredentialStatus(status),
        ),
      ]);
    } catch {
      // Non-critical load failure — keep existing state
    } finally {
      this.connectionsLoading.set(false);
    }
  }

  async refreshConnections(): Promise<void> {
    await this.platformsService.refreshConnections();
    // Also refresh settings to get latest ups_environment
    try {
      const settings = await firstValueFrom(this.apiService.getSettings());
      this.settingsStore.setAppSettings(settings);
    } catch {
      /* non-critical */
    }
  }

  toggleProvider(provider: string): void {
    this.openProvider.update((current) => (current === provider ? null : provider));
  }

  async handleDelete(connectionKey: string): Promise<void> {
    await this.platformsService.deleteProviderConnection(connectionKey);
    await this.refreshConnections();
  }

  async handleDisconnect(connectionKey: string): Promise<void> {
    await this.platformsService.disconnectProviderConnection(connectionKey);
    await this.refreshConnections();
  }

  async handleEnvSwitch(env: string): Promise<void> {
    const currentEnv = this.activeUpsEnv();
    if (env === currentEnv || this.envSwitching()) return;
    this.envSwitching.set(true);
    try {
      await firstValueFrom(this.apiService.patchSettings({ ups_environment: env as any }));
      const settings = await firstValueFrom(this.apiService.getSettings());
      this.settingsStore.setAppSettings(settings);
    } finally {
      this.envSwitching.set(false);
    }
  }

  isConnected(conn: ProviderConnectionInfo): boolean {
    return conn.status === 'connected';
  }

  isActiveEnv(env: string): boolean {
    const active = this.activeUpsEnv();
    return active === env || (!active && env === 'production');
  }

  getEnvButtonClass(env: string): string {
    const isActive = this.isActiveEnv(env);
    const isSwitching = this.envSwitching();
    const activeClasses = env === 'production'
      ? 'bg-success/10 border-success/40 text-success font-medium'
      : 'bg-info/10 border-info/40 text-info font-medium';
    const inactiveClasses = 'border-border text-muted-foreground hover:bg-muted/50';
    const disabledClasses = isSwitching ? ' opacity-50 cursor-not-allowed' : '';
    return (isActive ? activeClasses : inactiveClasses) + disabledClasses;
  }

  onCredentialSaved(): void {
    // Refresh credential status after saving Anthropic key
    firstValueFrom(this.apiService.getCredentialStatus())
      .then((status) => this.settingsStore.setCredentialStatus(status))
      .catch(() => { /* non-critical */ });
  }
}
