// shipagent-frontend/apps/settings-remote/src/app/address-book-section/contact-form.component.ts
/**
 * ContactFormComponent — Add/edit contact form with validation.
 *
 * Port of ContactForm.tsx React component.
 * Features:
 * - Handle auto-slug from display name
 * - Country dropdown with common codes
 * - Tag chips with add/remove
 */

import {
  ChangeDetectionStrategy,
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  signal,
  computed,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import type { Contact, ContactCreate, ContactUpdate } from '@shipagent/shared-types';

const COUNTRY_CODES = [
  { code: 'US', name: 'United States' },
  { code: 'CA', name: 'Canada' },
  { code: 'MX', name: 'Mexico' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'AU', name: 'Australia' },
  { code: 'JP', name: 'Japan' },
];

@Component({
  selector: 'app-contact-form',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule],
  template: `
    <form (ngSubmit)="handleSubmit()" class="space-y-4">

      <!-- Handle -->
      <div class="space-y-1.5">
        <label class="text-sm font-medium text-foreground">Handle</label>
        <div class="relative">
          <span class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground font-mono text-sm pointer-events-none">@</span>
          <input
            type="text"
            [(ngModel)]="handle"
            name="handle"
            placeholder="auto-generated if empty"
            class="w-full font-mono pl-7 px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
            (input)="onHandleInput($event)"
          />
        </div>
      </div>

      <!-- Display Name -->
      <div class="space-y-1.5">
        <label class="text-sm font-medium text-foreground">Display Name *</label>
        <input
          type="text"
          [(ngModel)]="displayName"
          name="displayName"
          placeholder="John Doe"
          required
          class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          (input)="onDisplayNameInput($event)"
        />
      </div>

      <!-- Company + Attention -->
      <div class="grid grid-cols-2 gap-3">
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-foreground">Company</label>
          <input
            type="text"
            [(ngModel)]="company"
            name="company"
            placeholder="Acme Inc"
            class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          />
        </div>
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-foreground">Attention</label>
          <input
            type="text"
            [(ngModel)]="attentionName"
            name="attentionName"
            placeholder="Shipping Dept"
            class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          />
        </div>
      </div>

      <!-- Phone + Email -->
      <div class="grid grid-cols-2 gap-3">
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-foreground">Phone</label>
          <input
            type="tel"
            [(ngModel)]="phone"
            name="phone"
            placeholder="+14155550100"
            class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          />
        </div>
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-foreground">Email</label>
          <input
            type="email"
            [(ngModel)]="email"
            name="email"
            placeholder="john@example.com"
            class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          />
        </div>
      </div>

      <!-- Address Line 1 -->
      <div class="space-y-1.5">
        <label class="text-sm font-medium text-foreground">Address Line 1 *</label>
        <input
          type="text"
          [(ngModel)]="addressLine1"
          name="addressLine1"
          placeholder="123 Main St"
          required
          class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
        />
      </div>

      <!-- Address Line 2 -->
      <div class="space-y-1.5">
        <label class="text-sm font-medium text-foreground">Address Line 2</label>
        <input
          type="text"
          [(ngModel)]="addressLine2"
          name="addressLine2"
          placeholder="Suite 100"
          class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
        />
      </div>

      <!-- City + State -->
      <div class="grid grid-cols-2 gap-3">
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-foreground">City *</label>
          <input
            type="text"
            [(ngModel)]="city"
            name="city"
            placeholder="San Francisco"
            required
            class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          />
        </div>
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-foreground">State/Province</label>
          <input
            type="text"
            [(ngModel)]="stateProvince"
            name="stateProvince"
            placeholder="CA"
            class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          />
        </div>
      </div>

      <!-- Postal + Country -->
      <div class="grid grid-cols-2 gap-3">
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-foreground">Postal Code *</label>
          <input
            type="text"
            [(ngModel)]="postalCode"
            name="postalCode"
            placeholder="94105"
            required
            class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          />
        </div>
        <div class="space-y-1.5">
          <label class="text-sm font-medium text-foreground">Country</label>
          <select
            [(ngModel)]="countryCode"
            name="countryCode"
            class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
          >
            @for (c of countries; track c.code) {
              <option [value]="c.code">{{ c.code }} — {{ c.name }}</option>
            }
          </select>
        </div>
      </div>

      <!-- Tags -->
      <div class="space-y-2">
        <label class="text-sm font-medium text-foreground">Tags</label>
        <div class="flex flex-wrap gap-1.5">
          @for (tag of tags(); track tag) {
            <span class="inline-flex items-center gap-1 px-2 py-0.5 bg-muted rounded text-xs">
              {{ tag }}
              <button
                type="button"
                (click)="removeTag(tag)"
                class="hover:text-destructive"
              >
                <svg class="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <line x1="18" y1="6" x2="6" y2="18"></line>
                  <line x1="6" y1="6" x2="18" y2="18"></line>
                </svg>
              </button>
            </span>
          }
        </div>
        <div class="flex gap-2">
          <input
            type="text"
            [(ngModel)]="tagInput"
            name="tagInput"
            placeholder="Add tag"
            class="flex-1 h-8 px-3 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
            (keydown.enter)="addTagOnEnter($event)"
          />
          <button
            type="button"
            (click)="addTag()"
            class="h-8 px-2.5 rounded-md border border-border text-muted-foreground hover:bg-muted transition-colors"
          >
            <svg class="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <line x1="12" y1="5" x2="12" y2="19"></line>
              <line x1="5" y1="12" x2="19" y2="12"></line>
            </svg>
          </button>
        </div>
      </div>

      <!-- Notes -->
      <div class="space-y-1.5">
        <label class="text-sm font-medium text-foreground">Notes</label>
        <textarea
          [(ngModel)]="notes"
          name="notes"
          placeholder="Additional notes..."
          rows="2"
          class="w-full px-3 py-2 rounded-md border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-1 focus:ring-primary/50"
        ></textarea>
      </div>

      <!-- Actions -->
      <div class="flex justify-end gap-2 pt-2">
        <button
          type="button"
          (click)="cancelled.emit()"
          class="px-4 py-2 rounded-md border border-border text-muted-foreground hover:bg-muted text-sm transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          [disabled]="!isValid() || isLoading"
          class="px-4 py-2 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 text-sm disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {{ isLoading ? 'Saving...' : (contact ? 'Update Contact' : 'Create Contact') }}
        </button>
      </div>
    </form>
  `,
})
export class ContactFormComponent implements OnInit {
  @Input() contact: Contact | null = null;
  @Input() isLoading = false;
  @Output() submitted = new EventEmitter<ContactCreate | ContactUpdate>();
  @Output() cancelled = new EventEmitter<void>();

  readonly countries = COUNTRY_CODES;

  // Form fields
  displayName = '';
  handle = '';
  private handleManuallyEdited = false;
  company = '';
  attentionName = '';
  phone = '';
  email = '';
  addressLine1 = '';
  addressLine2 = '';
  city = '';
  stateProvince = '';
  postalCode = '';
  countryCode = 'US';
  notes = '';

  tags = signal<string[]>([]);
  tagInput = '';

  isValid = computed(() => {
    return !!(this.displayName && this.addressLine1 && this.city && this.postalCode);
  });

  ngOnInit(): void {
    if (this.contact) {
      this.displayName = this.contact.display_name || '';
      this.handle = this.contact.handle || '';
      this.handleManuallyEdited = !!this.contact.handle;
      this.company = this.contact.company || '';
      this.attentionName = this.contact.attention_name || '';
      this.phone = this.contact.phone || '';
      this.email = this.contact.email || '';
      this.addressLine1 = this.contact.address_line_1 || '';
      this.addressLine2 = this.contact.address_line_2 || '';
      this.city = this.contact.city || '';
      this.stateProvince = this.contact.state_province || '';
      this.postalCode = this.contact.postal_code || '';
      this.countryCode = this.contact.country_code || 'US';
      this.notes = this.contact.notes || '';
      this.tags.set(this.contact.tags || []);
    }
  }

  onDisplayNameInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.displayName = value;
    if (!this.contact && !this.handleManuallyEdited) {
      this.handle = this.autoSlug(value);
    }
  }

  onHandleInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.handle = value.toLowerCase().replace(/[^a-z0-9-]/g, '');
    this.handleManuallyEdited = true;
  }

  private autoSlug(name: string): string {
    return name
      .toLowerCase()
      .replace(/'/g, '')
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 50);
  }

  addTagOnEnter(event: Event): void {
    event.preventDefault();
    this.addTag();
  }

  addTag(): void {
    const trimmed = this.tagInput.trim().toLowerCase();
    if (trimmed && !this.tags().includes(trimmed)) {
      this.tags.update((tags) => [...tags, trimmed]);
      this.tagInput = '';
    }
  }

  removeTag(tag: string): void {
    this.tags.update((tags) => tags.filter((t) => t !== tag));
  }

  handleSubmit(): void {
    if (!this.isValid()) return;

    const data: ContactCreate | ContactUpdate = {
      display_name: this.displayName,
      handle: this.handle || undefined,
      company: this.company || undefined,
      attention_name: this.attentionName || undefined,
      phone: this.phone || undefined,
      email: this.email || undefined,
      address_line_1: this.addressLine1,
      address_line_2: this.addressLine2 || undefined,
      city: this.city,
      state_province: this.stateProvince || undefined,
      postal_code: this.postalCode,
      country_code: this.countryCode,
      tags: this.tags().length > 0 ? this.tags() : undefined,
      notes: this.notes || undefined,
    };

    this.submitted.emit(data);
  }
}

// frontend/src/components/settings/ContactForm.tsx
/**
 * ContactForm - Add/edit contact form with validation.
 *
 * Features:
 * - Handle auto-slug from display name
 * - Country dropdown with common codes
 * - Usage checkboxes (ship_to, shipper, third_party)
 * - Tag chips with add/remove
 */

import * as React from 'react';
import { X, Plus } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import type { Contact, ContactCreate, ContactUpdate } from '@/types/api';

// Simple Label component
function Label({ htmlFor, children }: { htmlFor?: string; children: React.ReactNode }) {
  return (
    <label htmlFor={htmlFor} className="text-sm font-medium text-foreground">
      {children}
    </label>
  );
}

// Common country codes
const COUNTRY_CODES = [
  { code: 'US', name: 'United States' },
  { code: 'CA', name: 'Canada' },
  { code: 'MX', name: 'Mexico' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'AU', name: 'Australia' },
  { code: 'JP', name: 'Japan' },
];

interface ContactFormProps {
  contact?: Contact | null;
  onSubmit: (data: ContactCreate | ContactUpdate) => Promise<void>;
  onCancel: () => void;
  isLoading?: boolean;
}

export function ContactForm({
  contact,
  onSubmit,
  onCancel,
  isLoading,
}: ContactFormProps) {
  const isEditing = !!contact;

  // Form state
  const [displayName, setDisplayName] = React.useState(contact?.display_name || '');
  const [handle, setHandle] = React.useState(contact?.handle || '');
  const [handleManuallyEdited, setHandleManuallyEdited] = React.useState(!!contact?.handle);
  const [company, setCompany] = React.useState(contact?.company || '');
  const [attentionName, setAttentionName] = React.useState(contact?.attention_name || '');
  const [phone, setPhone] = React.useState(contact?.phone || '');
  const [email, setEmail] = React.useState(contact?.email || '');
  const [addressLine1, setAddressLine1] = React.useState(contact?.address_line_1 || '');
  const [addressLine2, setAddressLine2] = React.useState(contact?.address_line_2 || '');
  const [city, setCity] = React.useState(contact?.city || '');
  const [stateProvince, setStateProvince] = React.useState(contact?.state_province || '');
  const [postalCode, setPostalCode] = React.useState(contact?.postal_code || '');
  const [countryCode, setCountryCode] = React.useState(contact?.country_code || 'US');
  const [tags, setTags] = React.useState<string[]>(contact?.tags || []);
  const [tagInput, setTagInput] = React.useState('');
  const [notes, setNotes] = React.useState(contact?.notes || '');

  // Auto-slug handle from display name
  const autoSlugHandle = React.useCallback((name: string) => {
    return name
      .toLowerCase()
      .replace(/'/g, '')
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 50);
  }, []);

  const handleDisplayNameChange = (value: string) => {
    setDisplayName(value);
    // Only auto-generate handle if creating new contact and user hasn't manually edited it
    if (!isEditing && !handleManuallyEdited) {
      setHandle(autoSlugHandle(value));
    }
  };

  const handleHandleChange = (value: string) => {
    setHandle(value.toLowerCase().replace(/[^a-z0-9-]/g, ''));
    setHandleManuallyEdited(true);
  };

  const addTag = () => {
    const trimmed = tagInput.trim().toLowerCase();
    if (trimmed && !tags.includes(trimmed)) {
      setTags([...tags, trimmed]);
      setTagInput('');
    }
  };

  const removeTag = (tag: string) => {
    setTags(tags.filter((t) => t !== tag));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const data: ContactCreate | ContactUpdate = {
      display_name: displayName,
      handle: handle || undefined,
      company: company || undefined,
      attention_name: attentionName || undefined,
      phone: phone || undefined,
      email: email || undefined,
      address_line_1: addressLine1,
      address_line_2: addressLine2 || undefined,
      city,
      state_province: stateProvince || undefined,
      postal_code: postalCode,
      country_code: countryCode,
      tags: tags.length > 0 ? tags : undefined,
      notes: notes || undefined,
    };

    await onSubmit(data);
  };

  const isValid = displayName && addressLine1 && city && postalCode;

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {/* Handle */}
      <div className="space-y-1.5">
        <Label htmlFor="handle">Handle</Label>
        <div className="relative">
          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground font-mono text-sm pointer-events-none">
            @
          </span>
          <Input
            id="handle"
            value={handle}
            onChange={(e) => handleHandleChange(e.target.value)}
            placeholder="auto-generated if empty"
            className="font-mono pl-7"
          />
        </div>
      </div>

      {/* Display Name */}
      <div className="space-y-1.5">
        <Label htmlFor="displayName">Display Name *</Label>
        <Input
          id="displayName"
          value={displayName}
          onChange={(e) => handleDisplayNameChange(e.target.value)}
          placeholder="John Doe"
          required
        />
      </div>

      {/* Company + Attention */}
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="company">Company</Label>
          <Input
            id="company"
            value={company}
            onChange={(e) => setCompany(e.target.value)}
            placeholder="Acme Inc"
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="attention">Attention</Label>
          <Input
            id="attention"
            value={attentionName}
            onChange={(e) => setAttentionName(e.target.value)}
            placeholder="Shipping Dept"
          />
        </div>
      </div>

      {/* Phone + Email */}
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="phone">Phone</Label>
          <Input
            id="phone"
            value={phone}
            onChange={(e) => setPhone(e.target.value)}
            placeholder="+14155550100"
            type="tel"
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="john@example.com"
            type="email"
          />
        </div>
      </div>

      {/* Address */}
      <div className="space-y-1.5">
        <Label htmlFor="address1">Address Line 1 *</Label>
        <Input
          id="address1"
          value={addressLine1}
          onChange={(e) => setAddressLine1(e.target.value)}
          placeholder="123 Main St"
          required
        />
      </div>

      <div className="space-y-1.5">
        <Label htmlFor="address2">Address Line 2</Label>
        <Input
          id="address2"
          value={addressLine2}
          onChange={(e) => setAddressLine2(e.target.value)}
          placeholder="Suite 100"
        />
      </div>

      {/* City, State, Postal, Country */}
      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="city">City *</Label>
          <Input
            id="city"
            value={city}
            onChange={(e) => setCity(e.target.value)}
            placeholder="San Francisco"
            required
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="state">State/Province</Label>
          <Input
            id="state"
            value={stateProvince}
            onChange={(e) => setStateProvince(e.target.value)}
            placeholder="CA"
          />
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-1.5">
          <Label htmlFor="postal">Postal Code *</Label>
          <Input
            id="postal"
            value={postalCode}
            onChange={(e) => setPostalCode(e.target.value)}
            placeholder="94105"
            required
          />
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="country">Country</Label>
          <select
            id="country"
            value={countryCode}
            onChange={(e) => setCountryCode(e.target.value)}
            className="flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
          >
            {COUNTRY_CODES.map((c) => (
              <option key={c.code} value={c.code}>
                {c.code} — {c.name}
              </option>
            ))}
          </select>
        </div>
      </div>


      {/* Tags */}
      <div className="space-y-2">
        <Label>Tags</Label>
        <div className="flex flex-wrap gap-1.5">
          {tags.map((tag) => (
            <span
              key={tag}
              className="inline-flex items-center gap-1 px-2 py-0.5 bg-muted rounded text-xs"
            >
              {tag}
              <button
                type="button"
                onClick={() => removeTag(tag)}
                className="hover:text-destructive"
              >
                <X className="h-3 w-3" />
              </button>
            </span>
          ))}
        </div>
        <div className="flex gap-2">
          <Input
            value={tagInput}
            onChange={(e) => setTagInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                e.preventDefault();
                addTag();
              }
            }}
            placeholder="Add tag"
            className="h-8 text-sm"
          />
          <Button type="button" variant="outline" size="sm" onClick={addTag}>
            <Plus className="h-3 w-3" />
          </Button>
        </div>
      </div>

      {/* Notes */}
      <div className="space-y-1.5">
        <Label htmlFor="notes">Notes</Label>
        <textarea
          id="notes"
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Additional notes..."
          rows={2}
          className="flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        />
      </div>

      {/* Actions */}
      <div className="flex justify-end gap-2 pt-2">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit" disabled={!isValid || isLoading}>
          {isLoading ? 'Saving...' : isEditing ? 'Update Contact' : 'Create Contact'}
        </Button>
      </div>
    </form>
  );
}

export default ContactForm;
