// shipagent-frontend/apps/shell/src/app/update-checker/update-checker.component.ts
/**
 * UpdateCheckerComponent — Tauri auto-updater integration.
 *
 * Port of React UpdateChecker.tsx.
 * Only activates when running inside the Tauri desktop wrapper.
 * Checks for updates via @tauri-apps/plugin-updater and shows a banner
 * when an update is available.
 */
import {
  ChangeDetectionStrategy,
  Component,
  OnInit,
  inject,
  signal,
} from '@angular/core';
import { TauriDetectionService } from '@shipagent/shared-tauri';

@Component({
  selector: 'app-update-checker',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (updateAvailable()) {
      <div
        class="fixed bottom-4 right-4 z-40 flex items-center gap-3 rounded-lg border
               border-primary/30 bg-card px-4 py-3 shadow-lg"
        role="status"
        aria-live="polite"
      >
        <div class="flex-1">
          <p class="text-sm font-medium text-foreground">Update available</p>
          <p class="text-xs text-muted-foreground">{{ updateVersion() }} is ready to install.</p>
        </div>
        <button
          (click)="installUpdate()"
          class="btn-primary text-xs px-3 py-1.5"
          [disabled]="installing()"
        >
          {{ installing() ? 'Installing...' : 'Install' }}
        </button>
        <button
          (click)="dismissUpdate()"
          class="text-muted-foreground hover:text-foreground transition-colors"
          aria-label="Dismiss update notification"
        >
          &times;
        </button>
      </div>
    }
  `,
})
export class UpdateCheckerComponent implements OnInit {
  private readonly tauriDetection = inject(TauriDetectionService);

  protected readonly updateAvailable = signal(false);
  protected readonly updateVersion = signal<string>('');
  protected readonly installing = signal(false);

  // Store the updater object for later installation
  private updaterRef: unknown = null;

  ngOnInit(): void {
    if (this.tauriDetection.isTauri()) {
      this.checkForUpdates();
    }
  }

  private async checkForUpdates(): Promise<void> {
    try {
      // Dynamic import to avoid errors outside Tauri.
      // @tauri-apps/plugin-updater is only available in the bundled Tauri app.
      // We use Function() constructor to bypass TypeScript's static module analysis.
      const dynamicImport = new Function('modulePath', 'return import(modulePath)') as (p: string) => Promise<Record<string, unknown>>;
      const updaterModule = await dynamicImport('@tauri-apps/plugin-updater');
      const check = updaterModule['check'] as () => Promise<{ available: boolean; version?: string } | null>;
      const update = await check();
      if (update?.available) {
        this.updaterRef = update;
        this.updateVersion.set(update.version ?? 'New version');
        this.updateAvailable.set(true);
      }
    } catch {
      // Not in Tauri or plugin not available — silently ignore
    }
  }

  protected async installUpdate(): Promise<void> {
    if (!this.updaterRef || this.installing()) return;
    this.installing.set(true);
    try {
      const updater = this.updaterRef as { downloadAndInstall: () => Promise<void> };
      await updater.downloadAndInstall();
      // Tauri will restart the app after installation
    } catch (err) {
      console.error('[shell] Update installation failed:', err);
      this.installing.set(false);
    }
  }

  protected dismissUpdate(): void {
    this.updateAvailable.set(false);
  }
}

// frontend/src/components/settings/UpdateChecker.tsx
/**
 * Auto-update checker for the Tauri desktop app.
 *
 * Checks for updates on mount and every 4 hours. Shows a non-intrusive
 * banner when an update is available, with "Update Now" and "Later" buttons.
 * Only renders inside Tauri — hidden in Vite dev mode.
 */

import { useEffect, useState } from 'react';

interface UpdateInfo {
  version: string;
  body: string;
}

export function UpdateChecker() {
  const [update, setUpdate] = useState<UpdateInfo | null>(null);
  const [installing, setInstalling] = useState(false);

  useEffect(() => {
    if (!(window as any).__TAURI__) return;

    async function checkForUpdate() {
      try {
        const { check } = await import('@tauri-apps/plugin-updater');
        const result = await check();
        if (result?.available) {
          setUpdate({
            version: result.version,
            body: result.body ?? 'Bug fixes and improvements.',
          });
        }
      } catch (err) {
        console.warn('Update check failed:', err);
      }
    }

    checkForUpdate();
    const interval = setInterval(checkForUpdate, 4 * 60 * 60 * 1000);
    return () => clearInterval(interval);
  }, []);

  if (!update) return null;

  async function handleInstall() {
    setInstalling(true);
    try {
      const { check } = await import('@tauri-apps/plugin-updater');
      const result = await check();
      if (result?.available) {
        await result.downloadAndInstall();
      }
    } catch (err) {
      console.error('Update install failed:', err);
      setInstalling(false);
    }
  }

  return (
    <div className="fixed bottom-4 right-4 z-50 max-w-sm rounded-lg border
                    border-cyan-500/30 bg-gray-900 p-4 shadow-lg">
      <p className="text-sm font-medium text-white">
        ShipAgent {update.version} is available
      </p>
      <p className="mt-1 text-xs text-gray-400 line-clamp-2">{update.body}</p>
      <div className="mt-3 flex gap-2">
        <button
          onClick={handleInstall}
          disabled={installing}
          className="btn-primary text-xs"
        >
          {installing ? 'Installing...' : 'Update Now'}
        </button>
        <button
          onClick={() => setUpdate(null)}
          className="btn-secondary text-xs"
        >
          Later
        </button>
      </div>
    </div>
  );
}
